# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Azure Pipelines

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'mvn test'
  displayName: 'Execute Cucumber Tests'

- powershell: |
   $url = 'https://pulse-7.qtestnet.com/webhook/1aac2b57-92f5-41eb-aa28-5b9f87be67be'
   
   $content = Get-Content "Macintosh HD/Users/alfredquerubin/Documents/qTestAutomation/Cucumber/Result/cucumber-report.json" -Raw
   $bytes = [System.Text.Encoding]::ASCII.GetBytes($content)
   $payload = [System.Convert]::ToBase64String($bytes)
   
   $body = @{
    'projectId' = '127692'
    'testcycle' = '3676827'
    'result' = $payload
   }
   
   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
   Invoke-RestMethod -Body $body -Method 'Post' -Uri $url
  displayName: 'Upload Results to qTest Pulse'