# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

stages:
- stage: build

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

-stage: Publish

steps:
- task: PublishTestResults@1
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: 'C:\Tricentis\Automation\OpenSourceFrameworks\Cucumber\target\cucumber-report.json.xml'

- stage: Upload

- powershell: |
   $url = 'https://pulse-7.qtestnet.com/webhook/0fd02d1e-47fc-4c3d-83f4-740ed24f2005'
   
   $content = Get-Content "C:\Tricentis\Automation\OpenSourceFrameworks\Cucumber\target\cucumber-report.json.xml" -Raw
   $bytes = [System.Text.Encoding]::ASCII.GetBytes($content)
   $payload = [System.Convert]::ToBase64String($bytes)
   
   $body = @{
    'projectId' = '87143'
    'testcycle' = '2598404'
    'result' = $payload
   }
   
   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
   Invoke-RestMethod -Body $body -Method 'Post' -Uri $url
